name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.in
        pip install -r requirements.in

    - name: Lint with ruff
      run: |
        ruff check .

    - name: Format with black and ruff
      run: |
        black --check .
        ruff format --check .

    - name: Type check with mypy
      run: |
        mypy .

    # - name: Test with pytest
    #   run: |
    #     pytest
